import 'package:recase/recase.dart';

/// String utility extensions for code generation.
extension StringUtilsExtension on String {
  /// Convert to snake_case.
  String get toSnakeCase => ReCase(this).snakeCase;

  /// Convert to PascalCase.
  String get toPascalCase => ReCase(this).pascalCase;

  /// Convert to camelCase.
  String get toCamelCase => ReCase(this).camelCase;

  /// Convert to kebab-case.
  String get toKebabCase => ReCase(this).paramCase;

  /// Convert to CONSTANT_CASE.
  String get toConstantCase => ReCase(this).constantCase;
}

/// Utility class for common string operations in code generation.
class StringUtils {
  StringUtils._();

  /// Generate a proper Dart import path from a feature name and file name.
  static String importPath(String packageName, String featureName, String layer,
      String sublayer, String fileName) {
    return 'package:$packageName/features/$featureName/$layer/$sublayer/$fileName';
  }

  /// Generate a relative import path.
  static String relativeImport(String from, String to) {
    // Simple relative path calculation
    return to;
  }

  /// Convert a type string to a safe file name.
  static String typeToFileName(String type) {
    return type.toSnakeCase;
  }

  /// Indent a block of code by the given number of spaces.
  static String indent(String code, int spaces) {
    final prefix = ' ' * spaces;
    return code
        .split('\n')
        .map((line) => line.isEmpty ? line : '$prefix$line')
        .join('\n');
  }

  /// Wrap code in a standard Dart file header.
  static String fileHeader(String description) {
    return '// Generated by clean_feature_gen\n'
        '// $description\n'
        '// DO NOT modify by hand — re-run the generator to update.\n\n';
  }

  /// Generate a part directive.
  static String partDirective(String fileName) {
    return "part '$fileName';";
  }

  /// Generate a part of directive.
  static String partOfDirective(String fileName) {
    return "part of '$fileName';";
  }
}
